name: Deploy to VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker pull quirii/flask-api:latest
            docker run -d -p 80:80 quirii/flask-api
